name: finapp
description: Aplicacion de finanzas personales offline.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- GESTIÓN DE ESTADO ---
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # --- BASE DE DATOS ---
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # --- UI & NAVEGACIÓN ---
  go_router: ^13.2.0
  fl_chart: ^0.66.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  gap: ^3.0.0

  # --- UTILIDADES ---
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- GENERADORES DE CÓDIGO ---
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  
  # --- LINTERS (Solo el básico de Flutter) ---
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true